[server]
port = 6379                       # 服务器端口
expire_check_interval_secs = 1000 # 检查过期键的频率

[replication]
max_replicate = 10 # 最多允许多少个从服务器连接到当前服务器

[rdb]
enable = true          # 是否开启RDB持久化
file_path = "dump.rdb" # RDB文件路径
version = 1            # RDB版本
enable_checksum = true # 是否开启RDB校验和

[aof]
enable = true                # 是否开启AOF持久化
file_path = "appendonly.aof" # AOF文件路径
append_fsync = "everysec"    # AOF同步频率。可能为：always | everysec | no
